"use client";
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useRouter, useParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas-pro';

// Excalidraw is client-side only
const Excalidraw = dynamic(
  async () => (await import("@excalidraw/excalidraw")).Excalidraw,
  { ssr: false }
);

const exportToBlob = async (opts: any) => {
    const mod = await import("@excalidraw/excalidraw");
    return mod.exportToBlob(opts);
};

export default function MeetingDocumentViewer() {
    const router = useRouter();
    const params = useParams();
    const meetingId = params.id as string;

    const [loading, setLoading] = useState(true);
    const [docs, setDocs] = useState<any>({});
    const [meetingInfo, setMeetingInfo] = useState<any>(null);
    const [activeTab, setActiveTab] = useState<string>('canvas');
    const [exporting, setExporting] = useState(false);

    const contentRef = useRef<HTMLDivElement>(null);
    const excalidrawAPIs = useRef<Record<string, any>>({});

    useEffect(() => {
        const fetchDocs = async () => {
            try {
                const res = await fetch(`/api/dashboard/documents/${meetingId}`);
                const data = await res.json();
                if (data.success) {
                    setDocs(data.docs);
                    setMeetingInfo(data.meeting);

                    // Auto-select first available tab
                    if (data.docs.canvas) setActiveTab('canvas');
                    else if (data.docs.mindmap) setActiveTab('mindmap');
                    else if (data.docs.stickyNotes) setActiveTab('stickyNotes');
                    else if (data.docs.swot) setActiveTab('swot');
                }
            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        };
        fetchDocs();
    }, [meetingId]);

    // ─── PDF Export Handler ───────────────────────────────────────────
    const handleExportPDF = useCallback(async () => {
        if (exporting || !contentRef.current) return;
        setExporting(true);

        try {
            const pdf = new jsPDF({ 
                orientation: 'landscape', 
                unit: 'mm', 
                format: 'a4',
                compress: false 
            });
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            // ── Cover Page ───────────────────────────────────────────
            pdf.setFillColor(30, 27, 75);
            pdf.rect(0, 0, pageWidth, pageHeight, 'F');
            pdf.setFillColor(99, 102, 241);
            pdf.rect(0, pageHeight * 0.65, pageWidth, 4, 'F');

            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(36);
            pdf.setFont('helvetica', 'bold');
            const title = meetingInfo?.title || 'Meeting Report';
            pdf.text(title, pageWidth / 2, pageHeight * 0.38, { align: 'center' });

            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(165, 180, 252);
            pdf.text('Official Meeting Document', pageWidth / 2, pageHeight * 0.46, { align: 'center' });

            pdf.setFontSize(11);
            pdf.setTextColor(199, 210, 254);
            const dateStr = meetingInfo?.endedAt
                ? new Date(meetingInfo.endedAt).toLocaleString(undefined, {
                    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
                    hour: '2-digit', minute: '2-digit'
                })
                : 'Date unavailable';
            pdf.text(dateStr, pageWidth / 2, pageHeight * 0.52, { align: 'center' });

            pdf.setFontSize(10);
            pdf.setTextColor(129, 140, 248);
            pdf.text('Generated by Ideora', pageWidth / 2, pageHeight * 0.90, { align: 'center' });

            const tabOrder = ['canvas', 'mindmap', 'stickyNotes', 'swot'];
            const availableTabs = tabOrder.filter(tab => docs[tab]);

            const tabLabels: Record<string, string> = {
                canvas: 'Canvas / Whiteboard',
                mindmap: 'Mind Map',
                stickyNotes: 'Sticky Notes',
                swot: 'SWOT Analysis'
            };

            const originalTab = activeTab;

            for (const tab of availableTabs) {
                setActiveTab(tab);
                await new Promise(resolve => setTimeout(resolve, tab === 'swot' ? 800 : 2000));

                const element = contentRef.current;
                if (!element) continue;

                try {
                    let imgData = '';
                    let imgW: number = 0;
                    let imgH: number = 0;

                    pdf.addPage('a4', 'landscape');
                    pdf.setFillColor(248, 250, 252);
                    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
                    pdf.setFillColor(30, 27, 75);
                    pdf.rect(0, 0, pageWidth, 14, 'F');
                    pdf.setTextColor(255, 255, 255);
                    pdf.setFontSize(13);
                    pdf.setFont('helvetica', 'bold');
                    pdf.text(tabLabels[tab] || tab, 10, 9);

                    pdf.setFontSize(9);
                    pdf.setFont('helvetica', 'normal');
                    pdf.setTextColor(199, 210, 254);
                    pdf.text(title, pageWidth - 10, 9, { align: 'right' });

                    if (tab !== 'swot' && docs[tab]) {
                        try {
                            const state = typeof docs[tab] === 'string' ? JSON.parse(docs[tab]) : docs[tab];
                            const elements = state.elements || [];
                            
                            if (elements.length === 0) {
                                console.warn(`No elements to export on tab ${tab}`);
                                continue;
                            }

                            const blob = await exportToBlob({
                                elements,
                                mimeType: "image/png",
                                appState: state.appState || { theme: "light" },
                                exportPadding: 20,
                            });
                            
                            imgData = await new Promise((resolve) => {
                                const reader = new FileReader();
                                reader.onloadend = () => resolve(reader.result as string);
                                reader.readAsDataURL(blob);
                            });

                            const contentTop = 18;
                            const availableWidth = pageWidth - 20;
                            const availableHeight = pageHeight - contentTop - 10;
                            
                            // We don't have exact dimensions from blob easily without loading into an image
                            // so we'll use a standard fitting logic or just take a default
                            imgW = availableWidth;
                            imgH = availableHeight;
                        } catch (err) {
                            console.error(`Excalidraw export failed for ${tab}`, err);
                            continue;
                        }
                    } else {
                        const canvas = await html2canvas(element, {
                            scale: 2,
                            useCORS: true,
                            backgroundColor: '#f8fafc',
                        });
                        imgData = canvas.toDataURL('image/jpeg', 0.8);
                        imgW = pageWidth - 20;
                        imgH = (pageWidth - 20) / (canvas.width / canvas.height);
                    }

                    const marginContentTop = 18;
                    const imgX = (pageWidth - imgW) / 2;
                    const imgY = marginContentTop + ((pageHeight - marginContentTop - 10) - imgH) / 2;

                    pdf.addImage(imgData, 'PNG', imgX, imgY, imgW, imgH, undefined, 'FAST');

                    pdf.setFontSize(8);
                    pdf.setTextColor(148, 163, 184);
                    pdf.text(
                        `Page ${pdf.getNumberOfPages() - 1} of ${availableTabs.length}  •  ${dateStr}`,
                        pageWidth / 2,
                        pageHeight - 4,
                        { align: 'center' }
                    );
                } catch (captureErr) {
                    console.error(`Failed to capture tab: ${tab}`, captureErr);
                }
            }

            setActiveTab(originalTab);
            const fileName = `${(meetingInfo?.title || 'Meeting-Report').replace(/[^a-zA-Z0-9]/g, '_')}_Document.pdf`;
            pdf.save(fileName);
        } catch (err) {
            console.error('PDF export failed:', err);
            alert('Failed to export PDF.');
        } finally {
            setExporting(false);
        }
    }, [exporting, docs, meetingInfo, activeTab]);

    const renderExcalidrawBoard = (toolType: string) => {
        const state = docs[toolType];
        if (!state) return null;

        const parsedState = typeof state === 'string' ? JSON.parse(state) : state;

        return (
            <div className="w-full h-[700px] border border-slate-200 rounded-2xl overflow-hidden bg-white shadow-xl relative mt-4 isolate">
                <Excalidraw
                    excalidrawAPI={(api: any) => {
                        excalidrawAPIs.current[toolType] = api;
                    }}
                    initialData={{
                        elements: parsedState.elements || [],
                        appState: { ...parsedState.appState, viewModeEnabled: true, theme: "light" },
                        scrollToContent: true
                    }}
                    viewModeEnabled={true}
                    theme="light"
                />
            </div>
        );
    };

    const renderSwot = () => {
        const state = docs['swot'];
        if (!state) return null;
        let parsed = { strengths: [], weaknesses: [], opportunities: [], threats: [] };
        try {
            parsed = typeof state === 'string' ? JSON.parse(state) : state;
        } catch (e) { }

        return (
            <div className="w-full h-[700px] border border-slate-200 rounded-2xl overflow-hidden bg-white shadow-xl p-8 mt-4 grid grid-cols-2 gap-6">
                {['strengths', 'weaknesses', 'opportunities', 'threats'].map((quadrant) => {
                    const bgMap: any = {
                        strengths: 'bg-emerald-50 border-emerald-200 text-emerald-900',
                        weaknesses: 'bg-rose-50 border-rose-200 text-rose-900',
                        opportunities: 'bg-blue-50 border-blue-200 text-blue-900',
                        threats: 'bg-amber-50 border-amber-200 text-amber-900'
                    };
                    const qKey = quadrant as keyof typeof parsed;
                    return (
                        <div key={quadrant} className={`p-6 rounded-2xl border-2 ${bgMap[quadrant]} h-full overflow-y-auto`}>
                            <h3 className="uppercase font-black text-xl mb-6 flex items-center gap-3">
                                <div className="w-8 h-8 rounded-full bg-white flex items-center justify-center shadow-sm">
                                    {quadrant.charAt(0)}
                                </div>
                                {quadrant}
                            </h3>
                            <ul className="space-y-3">
                                {parsed[qKey]?.map((item: string, index: number) => (
                                    <li key={index} className="bg-white/60 backdrop-blur-sm px-4 py-3 rounded-xl shadow-sm border border-white/40 font-medium">
                                        {item}
                                    </li>
                                ))}
                                {(!parsed[qKey] || parsed[qKey].length === 0) && (
                                    <span className="text-sm opacity-50 italic">No nodes added</span>
                                )}
                            </ul>
                        </div>
                    );
                })}
            </div>
        );
    }

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center flex-col">
                <div className="w-16 h-16 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-6"></div>
                <h2 className="text-xl font-bold text-slate-700">Loading Visual Document...</h2>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
            <header className="bg-white border-b border-slate-200 px-8 py-5 flex items-center justify-between sticky top-0 z-50 shadow-sm">
                <div className="flex items-center gap-6">
                    <button
                        onClick={() => router.push('/dashboard/documents')}
                        className="p-2.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl transition-colors flex items-center justify-center"
                        title="Back to Vault"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                    </button>
                    <div className="h-10 w-px bg-slate-200"></div>
                    <div>
                        <div className="flex items-center gap-3 mb-1">
                            <span className="bg-indigo-100 text-indigo-700 text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded border border-indigo-200">Official Record</span>
                            <h1 className="text-2xl font-black text-slate-900">{meetingInfo?.title || 'Meeting Report'}</h1>
                        </div>
                        <p className="text-sm text-slate-500 font-medium">
                            Interactive Visual Snapshot • {new Date(meetingInfo?.endedAt).toLocaleString()}
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-3">
                    <button
                        onClick={handleExportPDF}
                        disabled={exporting}
                        className={`px-6 py-2.5 font-bold rounded-xl shadow-lg transition-all flex items-center gap-2 transform hover:-translate-y-0.5 ${
                            exporting
                                ? 'bg-indigo-400 text-white cursor-wait'
                                : 'bg-slate-900 text-white hover:bg-indigo-600 hover:shadow-indigo-500/30'
                        }`}
                    >
                        {exporting ? "Exporting..." : "Export to PDF"}
                    </button>
                </div>
            </header>

            <main className="flex-1 p-8 max-w-7xl mx-auto w-full flex flex-col">
                <div className="flex items-center gap-2 mb-2 bg-white p-2 rounded-2xl shadow-sm border border-slate-200 inline-flex self-start">
                    {['canvas', 'mindmap', 'stickyNotes', 'swot'].map((tab) => {
                        if (!docs[tab]) return null;
                        const isSelected = activeTab === tab;
                        return (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`px-5 py-2.5 font-bold text-sm capitalize rounded-xl transition-all flex items-center gap-2 ${isSelected ? 'bg-indigo-600 text-white shadow-md' : 'bg-transparent text-slate-500 hover:bg-slate-100'}`}
                            >
                                {tab.replace(/([A-Z])/g, ' $1').trim()}
                            </button>
                        )
                    })}
                </div>

                <div ref={contentRef}>
                    {activeTab === 'canvas' && renderExcalidrawBoard('canvas')}
                    {activeTab === 'mindmap' && renderExcalidrawBoard('mindmap')}
                    {activeTab === 'stickyNotes' && renderExcalidrawBoard('stickyNotes')}
                    {activeTab === 'swot' && renderSwot()}
                </div>
            </main>
        </div>
    );
}
