"use client";
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useRouter, useParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas-pro';

const BrainstormingMindmapping = dynamic(() => import('@/app/brainstorming/brainstormingMindmapping').then(mod => mod.default), { ssr: false });
const BrainstormingStickyNotes = dynamic(() => import('@/app/brainstorming/brainstormingStickyNotes').then(mod => mod.default), { ssr: false });
const BrainstormingCanvas = dynamic(() => import('@/app/brainstorming/brainstormingCanvas').then(mod => mod.default), { ssr: false });
const BrainstormingSwotAnalysis = dynamic(() => import('@/app/brainstorming/brainstormingSwotAnalysis').then(mod => mod.default), { ssr: false });

export default function MeetingDocumentViewer() {
    const router = useRouter();
    const params = useParams();
    const meetingId = params.id as string;

    const [loading, setLoading] = useState(true);
    const [docs, setDocs] = useState<any>({});
    const [meetingInfo, setMeetingInfo] = useState<any>(null);
    const [activeTab, setActiveTab] = useState<string>('canvas');
    const [exporting, setExporting] = useState(false);

    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const fetchDocs = async () => {
            try {
                const res = await fetch(`/api/dashboard/documents/${meetingId}`);
                const data = await res.json();
                if (data.success) {
                    setDocs(data.docs);
                    setMeetingInfo(data.meeting);

                    // Auto-select first available tab
                    if (data.docs.canvas) setActiveTab('canvas');
                    else if (data.docs.mindmap) setActiveTab('mindmap');
                    else if (data.docs.stickyNotes) setActiveTab('stickyNotes');
                    else if (data.docs.swot) setActiveTab('swot');
                }
            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        };
        fetchDocs();
    }, [meetingId]);

    // ─── PDF Export Handler ───────────────────────────────────────────
    const handleExportPDF = useCallback(async () => {
        if (exporting || !contentRef.current) return;
        setExporting(true);

        try {
            const pdf = new jsPDF({ 
                orientation: 'landscape', 
                unit: 'mm', 
                format: 'a4',
                compress: false 
            });
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            // ── Cover Page ───────────────────────────────────────────
            pdf.setFillColor(30, 27, 75); // dark indigo
            pdf.rect(0, 0, pageWidth, pageHeight, 'F');
            pdf.setFillColor(99, 102, 241); // indigo-500
            pdf.rect(0, pageHeight * 0.65, pageWidth, 4, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(36);
            pdf.setFont('helvetica', 'bold');
            const title = meetingInfo?.title || 'Meeting Report';
            pdf.text(title, pageWidth / 2, pageHeight * 0.38, { align: 'center' });
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(165, 180, 252); // indigo-300
            pdf.text('Official Meeting Document', pageWidth / 2, pageHeight * 0.46, { align: 'center' });
            pdf.setFontSize(11);
            pdf.setTextColor(199, 210, 254); // indigo-200
            const dateStr = meetingInfo?.endedAt
                ? new Date(meetingInfo.endedAt).toLocaleString(undefined, {
                    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
                    hour: '2-digit', minute: '2-digit'
                })
                : 'Date unavailable';
            pdf.text(dateStr, pageWidth / 2, pageHeight * 0.52, { align: 'center' });
            pdf.setFontSize(10);
            pdf.setTextColor(129, 140, 248); // indigo-400
            pdf.text('Generated by Ideora', pageWidth / 2, pageHeight * 0.90, { align: 'center' });

            // ── Capture Each Available Tab ──────────────────────────
            const tabOrder = ['canvas', 'mindmap', 'stickyNotes', 'swot'];
            const availableTabs = tabOrder.filter(tab => docs[tab]);
            const tabLabels: Record<string, string> = {
                canvas: 'Canvas / Whiteboard',
                mindmap: 'Mind Map',
                stickyNotes: 'Sticky Notes',
                swot: 'SWOT Analysis'
            };

            const originalTab = activeTab;

            for (const tab of availableTabs) {
                setActiveTab(tab);
                // Wait for the tab to render and components to load
                await new Promise(resolve => setTimeout(resolve, tab === 'canvas' ? 3500 : 3000));

                const element = contentRef.current;
                if (!element) continue;

                try {
                    let imgData = '';
                    let imgW: number = 0;
                    let imgH: number = 0;

                    pdf.addPage('a4', 'landscape');
                    pdf.setFillColor(248, 250, 252);
                    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
                    pdf.setFillColor(30, 27, 75);
                    pdf.rect(0, 0, pageWidth, 14, 'F');
                    pdf.setTextColor(255, 255, 255);
                    pdf.setFontSize(13);
                    pdf.setFont('helvetica', 'bold');
                    pdf.text(tabLabels[tab] || tab, 10, 9);
                    pdf.setFontSize(9);
                    pdf.setFont('helvetica', 'normal');
                    pdf.setTextColor(199, 210, 254);
                    pdf.text(title, pageWidth - 10, 9, { align: 'right' });

                    const canvas = await html2canvas(element, {
                        scale: 2,
                        useCORS: true,
                        logging: false,
                        backgroundColor: tab === 'mindmap' || tab === 'stickyNotes' ? '#0f172a' : '#f8fafc',
                        onclone: (clonedDoc) => {
                            // Aggressively hide UI components in the capture
                            const selectors = [
                                '.react-flow__controls', 
                                '.react-flow__minimap', 
                                'button', 
                                '.absolute.bottom-4.left-4',
                                '.absolute.bottom-6.left-28'
                            ];
                            selectors.forEach(s => {
                                clonedDoc.querySelectorAll(s).forEach(el => {
                                    (el as HTMLElement).style.setProperty('display', 'none', 'important');
                                });
                            });
                            const rf = clonedDoc.querySelector('.react-flow') as HTMLElement;
                            if (rf) rf.style.backgroundColor = tab === 'mindmap' || tab === 'stickyNotes' ? '#0f172a' : '#f8fafc';
                        }
                    });
                    
                    if (!canvas || canvas.width === 0 || canvas.height === 0) {
                        console.error(`Capture failed for tab: ${tab}`);
                        continue;
                    }

                    imgData = canvas.toDataURL('image/jpeg', 0.95);
                    const imgAspect = canvas.width / canvas.height;
                    const slotAspect = (pageWidth - 20) / (pageHeight - 28);

                    if (!isFinite(imgAspect) || isNaN(imgAspect)) {
                        console.error(`Invalid aspect ratio for tab: ${tab}`);
                        continue;
                    }

                    if (imgAspect > slotAspect) {
                        imgW = pageWidth - 20;
                        imgH = (pageWidth - 20) / imgAspect;
                    } else {
                        imgH = pageHeight - 28;
                        imgW = (pageHeight - 28) * imgAspect;
                    }

                    if (imgData && imgW > 0 && imgH > 0) {
                        const imgX = (pageWidth - imgW) / 2;
                        const imgY = 18 + ((pageHeight - 28) - imgH) / 2;
                        pdf.addImage(imgData, 'JPEG', imgX, imgY, imgW, imgH, undefined, 'FAST');
                    }

                    pdf.setFontSize(8);
                    pdf.setTextColor(148, 163, 184);
                    pdf.text(`Page ${pdf.getNumberOfPages() - 1} of ${availableTabs.length}  •  ${dateStr}`, pageWidth / 2, pageHeight - 4, { align: 'center' });
                } catch (captureErr) {
                    console.error(`Failed to capture tab: ${tab}`, captureErr);
                }
            }

            setActiveTab(originalTab);
            const fileName = `${(meetingInfo?.title || 'Meeting-Report').replace(/[^a-zA-Z0-9]/g, '_')}_Document.pdf`;
            pdf.save(fileName);

            try {
                const pdfBlob = pdf.output('blob');
                const uploadFormData = new FormData();
                uploadFormData.append('report', pdfBlob, fileName);
                uploadFormData.append('meetingId', meetingId);
                fetch('/api/meeting/uploadReport', { method: 'POST', body: uploadFormData });
            } catch (uploadErr) {}

        } catch (err) {
            console.error('PDF export failed:', err);
            alert('Failed to export PDF.');
        } finally {
            setExporting(false);
        }
    }, [exporting, docs, meetingInfo, activeTab, meetingId]);

    // ─── Component Rendering ──────────────────────────────────────────

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center flex-col">
                <div className="w-16 h-16 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-6"></div>
                <h2 className="text-xl font-bold text-slate-700">Loading Visual Document...</h2>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
            {/* Top Navigation Header */}
            <header className="bg-white border-b border-slate-200 px-4 sm:px-8 py-3 sm:py-5 flex flex-col sm:flex-row items-center justify-between sticky top-0 z-50 shadow-sm gap-4 sm:gap-0">
                <div className="flex items-center gap-3 sm:gap-6 w-full sm:w-auto">
                    <button
                        onClick={() => router.push('/dashboard/documents')}
                        className="p-2 sm:p-2.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl transition-colors flex items-center justify-center shrink-0"
                        title="Back to Vault"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                    </button>
                    <div className="h-8 sm:h-10 w-px bg-slate-200"></div>
                    <div className="min-w-0 flex-1">
                        <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-3 mb-0.5">
                            <span className="bg-indigo-100 text-indigo-700 text-[9px] sm:text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded border border-indigo-200 self-start shadow-sm">Official Record</span>
                            <h1 className="text-base sm:text-2xl font-black text-slate-900 truncate leading-tight">{meetingInfo?.title || 'Meeting Report'}</h1>
                        </div>
                        <p className="text-[10px] sm:text-sm text-slate-500 font-medium truncate">
                            Visual Snapshot • {new Date(meetingInfo?.endedAt).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-3 w-full sm:w-auto">
                    <button
                        onClick={handleExportPDF}
                        disabled={exporting}
                        className={`flex-1 sm:flex-none px-4 sm:px-6 py-2 sm:py-2.5 font-bold rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 transform hover:-translate-y-0.5 text-xs sm:text-sm ${
                            exporting
                                ? 'bg-indigo-400 text-white cursor-wait'
                                : 'bg-slate-900 text-white hover:bg-indigo-600 hover:shadow-indigo-500/30'
                        }`}
                    >
                        {exporting ? (
                            <>
                                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                <span className="hidden sm:inline">Exporting...</span>
                                <span className="sm:hidden">Exp...</span>
                            </>
                        ) : (
                            <>
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                                <span className="hidden xs:inline">Export to PDF</span>
                                <span className="xs:hidden">Export</span>
                            </>
                        )}
                    </button>
                </div>
            </header>

            <main className="flex-1 p-4 sm:p-8 max-w-7xl mx-auto w-full flex flex-col min-h-0 overflow-y-auto sm:overflow-visible">
                {/* Internal Tool Tabs - Horizontal Scroll on Mobile */}
                <div className="w-full overflow-hidden mb-2">
                    <div className="flex items-center gap-2 bg-white p-2 rounded-2xl shadow-sm border border-slate-200 overflow-x-auto no-scrollbar scroll-smooth">
                    {['canvas', 'mindmap', 'stickyNotes', 'swot'].map((tab) => {
                        if (!docs[tab]) return null;

                        const isSelected = activeTab === tab;
                        const icons: any = {
                            canvas: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />,
                            mindmap: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />,
                            stickyNotes: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />,
                            swot: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6a2 2 0 012-2h2a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
                        };

                        return (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`px-5 py-2.5 font-bold text-sm capitalize rounded-xl transition-all flex items-center gap-2 ${isSelected ? 'bg-indigo-600 text-white shadow-md' : 'bg-transparent text-slate-500 hover:bg-slate-100 hover:text-slate-800'}`}
                            >
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    {icons[tab]}
                                </svg>
                                {tab.replace(/([A-Z])/g, ' $1').trim()}
                            </button>
                        )
                    })}
                </div>
            </div>

                <div ref={contentRef} className="flex-1 flex flex-col h-[500px] sm:h-[700px] relative mt-2 sm:mt-4">
                    {activeTab === 'canvas' && (
                        <div className="absolute inset-0 rounded-xl overflow-hidden shadow-2xl bg-white border border-slate-200 z-10 w-full h-full">
                            <BrainstormingCanvas meetingId={meetingId || ""} readOnly={true} initialData={docs.canvas} />
                        </div>
                    )}
                    {activeTab === 'mindmap' && (
                        <div className="absolute inset-0 rounded-xl overflow-hidden shadow-2xl bg-slate-900 border border-slate-700 z-10 w-full h-full">
                            <BrainstormingMindmapping meetingId={meetingId || ""} readOnly={true} initialData={docs.mindmap} />
                        </div>
                    )}
                    {activeTab === 'stickyNotes' && (
                        <div className="absolute inset-0 rounded-xl overflow-hidden shadow-2xl bg-slate-900 border border-slate-700 z-10 w-full h-full">
                             <BrainstormingStickyNotes meetingId={meetingId || ""} readOnly={true} initialData={docs.stickyNotes} />
                        </div>
                    )}
                    {activeTab === 'swot' && (
                        <div className="flex-1 relative rounded-xl overflow-hidden shadow-2xl bg-slate-50 min-h-[600px] border border-slate-200">
                            <BrainstormingSwotAnalysis meetingId={meetingId || ""} readOnly={true} initialData={docs.swot} />
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
}
