"use client";
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useRouter, useParams } from 'next/navigation';
import type { Editor } from 'tldraw';
import dynamic from 'next/dynamic';
import "tldraw/tldraw.css";
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas-pro';

const Tldraw = dynamic(() => import('tldraw').then((mod) => mod.Tldraw), { ssr: false });

export default function MeetingDocumentViewer() {
    const router = useRouter();
    const params = useParams();
    const meetingId = params.id as string;

    const [loading, setLoading] = useState(true);
    const [docs, setDocs] = useState<any>({});
    const [meetingInfo, setMeetingInfo] = useState<any>(null);
    const [activeTab, setActiveTab] = useState<string>('canvas');
    const [exporting, setExporting] = useState(false);

    const contentRef = useRef<HTMLDivElement>(null);
    const editorRef = useRef<Editor | null>(null);

    useEffect(() => {
        const fetchDocs = async () => {
            try {
                const res = await fetch(`/api/dashboard/documents/${meetingId}`);
                const data = await res.json();
                if (data.success) {
                    setDocs(data.docs);
                    setMeetingInfo(data.meeting);

                    // Auto-select first available tab
                    if (data.docs.canvas) setActiveTab('canvas');
                    else if (data.docs.mindmap) setActiveTab('mindmap');
                    else if (data.docs.stickyNotes) setActiveTab('stickyNotes');
                    else if (data.docs.swot) setActiveTab('swot');
                }
            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        };
        fetchDocs();
    }, [meetingId]);

    // ─── PDF Export Handler ───────────────────────────────────────────
    const handleExportPDF = useCallback(async () => {
        if (exporting || !contentRef.current) return;
        setExporting(true);

        try {
            const pdf = new jsPDF({ 
                orientation: 'landscape', 
                unit: 'mm', 
                format: 'a4',
                compress: false 
            });
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            // ── Cover Page ───────────────────────────────────────────
            // Background
            pdf.setFillColor(30, 27, 75); // dark indigo
            pdf.rect(0, 0, pageWidth, pageHeight, 'F');

            // Accent stripe
            pdf.setFillColor(99, 102, 241); // indigo-500
            pdf.rect(0, pageHeight * 0.65, pageWidth, 4, 'F');

            // Title
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(36);
            pdf.setFont('helvetica', 'bold');
            const title = meetingInfo?.title || 'Meeting Report';
            pdf.text(title, pageWidth / 2, pageHeight * 0.38, { align: 'center' });

            // Subtitle
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(165, 180, 252); // indigo-300
            pdf.text('Official Meeting Document', pageWidth / 2, pageHeight * 0.46, { align: 'center' });

            // Date
            pdf.setFontSize(11);
            pdf.setTextColor(199, 210, 254); // indigo-200
            const dateStr = meetingInfo?.endedAt
                ? new Date(meetingInfo.endedAt).toLocaleString(undefined, {
                    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
                    hour: '2-digit', minute: '2-digit'
                })
                : 'Date unavailable';
            pdf.text(dateStr, pageWidth / 2, pageHeight * 0.52, { align: 'center' });

            // Branding
            pdf.setFontSize(10);
            pdf.setTextColor(129, 140, 248); // indigo-400
            pdf.text('Generated by Ideora', pageWidth / 2, pageHeight * 0.90, { align: 'center' });

            // ── Capture Each Available Tab ──────────────────────────
            const tabOrder = ['canvas', 'mindmap', 'stickyNotes', 'swot'];
            const availableTabs = tabOrder.filter(tab => docs[tab]);

            const tabLabels: Record<string, string> = {
                canvas: 'Canvas / Whiteboard',
                mindmap: 'Mind Map',
                stickyNotes: 'Sticky Notes',
                swot: 'SWOT Analysis'
            };

            const originalTab = activeTab;

            for (const tab of availableTabs) {
                // Switch to the tab so it renders
                setActiveTab(tab);

                // Wait for the tab to render (tldraw needs extra time)
                await new Promise(resolve => setTimeout(resolve, tab === 'swot' ? 800 : 2000));

                // For tldraw tabs, explicitly fix white arrows/shapes before capture
                if (tab !== 'swot' && editorRef.current) {
                    try {
                        const ed = editorRef.current;
                        ed.updateInstanceState({ isReadonly: false });
                        const shapes = ed.getCurrentPageShapes();
                        shapes.forEach((shape: any) => {
                            if (shape.props?.color === 'white') {
                                ed.updateShape({
                                    id: shape.id,
                                    type: shape.type,
                                    props: { color: 'black' }
                                });
                            }
                        });
                        ed.updateInstanceState({ isReadonly: true });
                        // Wait for visual DOM to re-render after color fix
                        await new Promise(resolve => setTimeout(resolve, 500));
                    } catch (e) {
                        console.error('Color fix during export failed:', e);
                    }
                }

                // Capture the content area
                const element = contentRef.current;
                if (!element) continue;

                try {
                    let imgData = '';
                    let imgW: number = 0;
                    let imgH: number = 0;

                    // Add a new page for each tab
                    pdf.addPage('a4', 'landscape');

                    // Section header bar
                    pdf.setFillColor(248, 250, 252); // slate-50
                    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
                    pdf.setFillColor(30, 27, 75); // dark indigo
                    pdf.rect(0, 0, pageWidth, 14, 'F');
                    pdf.setTextColor(255, 255, 255);
                    pdf.setFontSize(13);
                    pdf.setFont('helvetica', 'bold');
                    pdf.text(tabLabels[tab] || tab, 10, 9);

                    // Meeting title on the right side of the header
                    pdf.setFontSize(9);
                    pdf.setFont('helvetica', 'normal');
                    pdf.setTextColor(199, 210, 254);
                    pdf.text(title, pageWidth - 10, 9, { align: 'right' });

                    if (tab !== 'swot' && editorRef.current) {
                        try {
                            const editor = editorRef.current;
                            const shapeIds = Array.from(editor.getCurrentPageShapeIds());
                            if (shapeIds.length === 0) {
                                console.warn(`No shapes to export on tab ${tab}`);
                                continue;
                            }

                            // Use tldraw native export
                            const imageResult = await editor.toImage(shapeIds, {
                                format: 'png',
                                background: true,
                                padding: 32
                            });
                            
                            if (!imageResult || !imageResult.blob) {
                                throw new Error('toImage returned empty blob');
                            }

                            // Convert Blob to Data URL
                            imgData = await new Promise((resolve) => {
                                const reader = new FileReader();
                                reader.onloadend = () => resolve(reader.result as string);
                                reader.readAsDataURL(imageResult.blob);
                            });

                            const contentTop = 18; // mm from top
                            const availableWidth = pageWidth - 20; // 10mm margins
                            const availableHeight = pageHeight - contentTop - 10;
                            const imgAspect = imageResult.width / imageResult.height;
                            const slotAspect = availableWidth / availableHeight;

                            if (imgAspect > slotAspect) {
                                imgW = availableWidth;
                                imgH = availableWidth / imgAspect;
                            } else {
                                imgH = availableHeight;
                                imgW = availableHeight * imgAspect;
                            }

                        } catch (err) {
                            console.error(`Native tldraw export failed for ${tab}`, err);
                            continue;
                        }
                    } else {
                        // Fallback to html2canvas for swot table
                        const canvas = await html2canvas(element, {
                            scale: 3,
                            useCORS: true,
                            allowTaint: true,
                            backgroundColor: '#f8fafc',
                            logging: false
                        });
                        imgData = canvas.toDataURL('image/jpeg', 0.8);

                        const contentTop = 18;
                        const availableWidth = pageWidth - 20;
                        const availableHeight = pageHeight - contentTop - 10;
                        const imgAspect = canvas.width / canvas.height;
                        const slotAspect = availableWidth / availableHeight;

                        if (imgAspect > slotAspect) {
                            imgW = availableWidth;
                            imgH = availableWidth / imgAspect;
                        } else {
                            imgH = availableHeight;
                            imgW = availableHeight * imgAspect;
                        }
                    }

                    const marginContentTop = 18;
                    const imgX = (pageWidth - imgW) / 2;
                    const imgY = marginContentTop + ((pageHeight - marginContentTop - 10) - imgH) / 2;

                    pdf.addImage(imgData, imgData.startsWith('data:image/png') ? 'PNG' : 'JPEG', imgX, imgY, imgW, imgH, undefined, 'FAST');

                    // Footer
                    pdf.setFontSize(8);
                    pdf.setTextColor(148, 163, 184); // slate-400
                    pdf.text(
                        `Page ${pdf.getNumberOfPages() - 1} of ${availableTabs.length}  •  ${dateStr}`,
                        pageWidth / 2,
                        pageHeight - 4,
                        { align: 'center' }
                    );
                } catch (captureErr) {
                    console.error(`Failed to capture tab: ${tab}`, captureErr);
                }
            } // end for loop

            // Restore the original tab
            setActiveTab(originalTab);

            // Save the PDF locally
            const fileName = `${(meetingInfo?.title || 'Meeting-Report').replace(/[^a-zA-Z0-9]/g, '_')}_Document.pdf`;
            pdf.save(fileName);

            // Also upload to Cloudinary for permanent storage in meetingResources
            try {
                console.log('Starting cloud upload for brainstorming report...');
                const pdfBlob = pdf.output('blob');
                const uploadFormData = new FormData();
                uploadFormData.append('report', pdfBlob, fileName);
                uploadFormData.append('meetingId', meetingId);
                const uploadRes = await fetch('/api/meeting/uploadReport', {
                    method: 'POST',
                    body: uploadFormData,
                });
                const uploadData = await uploadRes.json();
                if (uploadData.success) {
                    console.log('Report uploaded to cloud:', uploadData.reportUrl);
                } else {
                    console.warn('Cloud upload failed:', uploadData.error);
                }
            } catch (uploadErr) {
                console.warn('Cloud upload error (PDF saved locally):', uploadErr);
            }
        } catch (err) {
            console.error('PDF export failed:', err);
            alert('Failed to export PDF. Please try again.');
        } finally {
            setExporting(false);
        }
    }, [exporting, docs, meetingInfo, activeTab]);

    const renderTldrawBoard = (toolType: string) => {
        const state = docs[toolType];
        if (!state) return null;

        return (
            <div className="w-full h-[700px] border border-slate-200 rounded-2xl overflow-hidden bg-white shadow-xl relative mt-4 isolate">
                <Tldraw
                    key={toolType}
                    hideUi={false}
                    onMount={(editor: Editor) => {
                        import('tldraw').then(({ loadSnapshot }) => {
                            try {
                                editorRef.current = editor;
                                editor.updateInstanceState({ isReadonly: true });
                                const parsedState = typeof state === 'string' ? JSON.parse(state) : state;

                                // Load snapshot based on format
                                if (parsedState.store) {
                                    // tldraw specific full snapshot format
                                    const records = Object.values(parsedState.store) as any[];

                                // Auto-convert any explicitly 'white' colored lines/arrows to 'black' for the light mode Viewer
                                records.forEach((record: any) => {
                                    if (record.typeName === 'shape' && record.props && record.props.color === 'white') {
                                        record.props.color = 'black';
                                    }
                                });

                                if (records.length > 0) {
                                    loadSnapshot(editor.store, parsedState);
                                }
                            } else {
                                // Direct generic record load
                                if (Array.isArray(parsedState)) {
                                    parsedState.forEach((record: any) => {
                                        if (record.typeName === 'shape' && record.props && record.props.color === 'white') {
                                            record.props.color = 'black';
                                        }
                                    });
                                }
                                loadSnapshot(editor.store, parsedState);
                            }

                            editor.user.updateUserPreferences({ colorScheme: 'light' });

                            // Post-load fix: convert white shapes/arrows to black AFTER snapshot fully settles
                            setTimeout(() => {
                                // Temporarily disable readonly so updateShape works
                                editor.updateInstanceState({ isReadonly: false });

                                const allShapes = editor.getCurrentPageShapes();
                                allShapes.forEach((shape: any) => {
                                    if (shape.props?.color === 'white') {
                                        editor.updateShape({
                                            id: shape.id,
                                            type: shape.type,
                                            props: { color: 'black' }
                                        });
                                    }
                                });

                                // Re-enable readonly after color fix
                                editor.updateInstanceState({ isReadonly: true });
                                // Zoom to fit after color fix
                                setTimeout(() => editor.zoomToFit(), 200);
                            }, 100);
                        } catch (e) {
                            console.error("Snapshot load error", e);
                        }
                        });
                    }}
                />
            </div>
        );
    };

    const renderSwot = () => {
        const state = docs['swot'];
        if (!state) return null;
        let parsed = { strengths: [], weaknesses: [], opportunities: [], threats: [] };
        try {
            parsed = typeof state === 'string' ? JSON.parse(state) : state;
        } catch (e) { }

        return (
            <div className="w-full h-[700px] border border-slate-200 rounded-2xl overflow-hidden bg-white shadow-xl p-8 mt-4 grid grid-cols-2 gap-6">
                {['strengths', 'weaknesses', 'opportunities', 'threats'].map((quadrant) => {
                    const bgMap: any = {
                        strengths: 'bg-emerald-50 border-emerald-200 text-emerald-900',
                        weaknesses: 'bg-rose-50 border-rose-200 text-rose-900',
                        opportunities: 'bg-blue-50 border-blue-200 text-blue-900',
                        threats: 'bg-amber-50 border-amber-200 text-amber-900'
                    };

                    const qKey = quadrant as keyof typeof parsed;

                    return (
                        <div key={quadrant} className={`p-6 rounded-2xl border-2 ${bgMap[quadrant]} h-full overflow-y-auto`}>
                            <h3 className="uppercase font-black text-xl mb-6 flex items-center gap-3">
                                <div className="w-8 h-8 rounded-full bg-white flex items-center justify-center shadow-sm">
                                    {quadrant.charAt(0)}
                                </div>
                                {quadrant}
                            </h3>
                            <ul className="space-y-3">
                                {parsed[qKey]?.map((item: string, index: number) => (
                                    <li key={index} className="bg-white/60 backdrop-blur-sm px-4 py-3 rounded-xl shadow-sm border border-white/40 font-medium">
                                        {item}
                                    </li>
                                ))}
                                {(!parsed[qKey] || parsed[qKey].length === 0) && (
                                    <span className="text-sm opacity-50 italic">No nodes added</span>
                                )}
                            </ul>
                        </div>
                    );
                })}
            </div>
        );
    }

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center flex-col">
                <div className="w-16 h-16 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-6"></div>
                <h2 className="text-xl font-bold text-slate-700">Loading Visual Document...</h2>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
            {/* Top Navigation Header */}
            <header className="bg-white border-b border-slate-200 px-8 py-5 flex items-center justify-between sticky top-0 z-50 shadow-sm">
                <div className="flex items-center gap-6">
                    <button
                        onClick={() => router.push('/dashboard/documents')}
                        className="p-2.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl transition-colors flex items-center justify-center"
                        title="Back to Vault"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                    </button>
                    <div className="h-10 w-px bg-slate-200"></div>
                    <div>
                        <div className="flex items-center gap-3 mb-1">
                            <span className="bg-indigo-100 text-indigo-700 text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded border border-indigo-200">Official Record</span>
                            <h1 className="text-2xl font-black text-slate-900">{meetingInfo?.title || 'Meeting Report'}</h1>
                        </div>
                        <p className="text-sm text-slate-500 font-medium">
                            Interactive Visual Snapshot • {new Date(meetingInfo?.endedAt).toLocaleString()}
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-3">
                    <button
                        onClick={handleExportPDF}
                        disabled={exporting}
                        className={`px-6 py-2.5 font-bold rounded-xl shadow-lg transition-all flex items-center gap-2 transform hover:-translate-y-0.5 ${
                            exporting
                                ? 'bg-indigo-400 text-white cursor-wait'
                                : 'bg-slate-900 text-white hover:bg-indigo-600 hover:shadow-indigo-500/30'
                        }`}
                    >
                        {exporting ? (
                            <>
                                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                Exporting...
                            </>
                        ) : (
                            <>
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                                Export to PDF
                            </>
                        )}
                    </button>
                </div>
            </header>

            <main className="flex-1 p-8 max-w-7xl mx-auto w-full flex flex-col">
                {/* Internal Tool Tabs */}
                <div className="flex items-center gap-2 mb-2 bg-white p-2 rounded-2xl shadow-sm border border-slate-200 inline-flex self-start">
                    {['canvas', 'mindmap', 'stickyNotes', 'swot'].map((tab) => {
                        if (!docs[tab]) return null;

                        const isSelected = activeTab === tab;
                        const icons: any = {
                            canvas: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />,
                            mindmap: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />,
                            stickyNotes: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />,
                            swot: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6a2 2 0 012-2h2a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
                        };

                        return (
                            <button
                                key={tab}
                                onClick={() => setActiveTab(tab)}
                                className={`px-5 py-2.5 font-bold text-sm capitalize rounded-xl transition-all flex items-center gap-2 ${isSelected ? 'bg-indigo-600 text-white shadow-md' : 'bg-transparent text-slate-500 hover:bg-slate-100 hover:text-slate-800'}`}
                            >
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    {icons[tab]}
                                </svg>
                                {tab.replace(/([A-Z])/g, ' $1').trim()}
                            </button>
                        )
                    })}
                </div>

                {/* Content area captured for PDF export */}
                <div ref={contentRef}>
                    {activeTab === 'canvas' && renderTldrawBoard('canvas')}
                    {activeTab === 'mindmap' && renderTldrawBoard('mindmap')}
                    {activeTab === 'stickyNotes' && renderTldrawBoard('stickyNotes')}
                    {activeTab === 'swot' && renderSwot()}
                </div>
            </main>
        </div>
    );
}
